### ISSUE TITLE
Small spectral elements

### ISSUE THREAD

**Issue by eikmeier-cn** [geodynamics/specfem3d#1501]
Hey guys.

I am trying to perform a simulation in a small volume (450 x 400 x 90 m) with two layers. The first layer is soil with low velocity values and the second layer is a gneiss. For the source I will use the injection of a signal with high frequencies (40Hz). So, my spectral elements must be small. For the first layer the size is 1.25m and for the second layer 11.25m. However, when I try to run the simulation, the following error appears:

![print_do_erro - Copia](https://user-images.githubusercontent.com/53953620/166968855-549ee193-923c-4060-aefe-10038ae28c75.jpg)

When I test the same scenario increasing the volume (40000 x 45000 x 9000m) and using 300m spectral elements for the first layer and 900m for the second layer, the same error does not happen.

The script that I used to create the first and the second case is the same, and for that I used Cubit.

Could anyone help me with this issue?

Thank you!

**Comment by eikmeier-cn** [comment]
I thought it could be related to the value of TOLERANCE_FACE_DETECTION = 1d-4, in constants.h. However, the code does not accept that I put a number greater than 1d-1, occurring a floating point error.

**Comment by eikmeier-cn** [comment]
Well, I said I had solved the problem, but another one cames up. A floating point error in the solver. Even setting all possible variables to double precision in `constants.h.in` and compiling the code, I couldn't solve this problem. Can  someone from the Specfem team helpe me with this?

![image](https://user-images.githubusercontent.com/53953620/167273137-5dce238f-67fa-4f95-aebd-405c9aafc7dd.png)

**Comment by eikmeier-cn** [comment]
Problem solved. The problem was in the DT. The rule exposed in the manual can fail in several situations. So we need to decrease the dt until it works.

**Comment by danielpeter** [comment]
when looking at the face detection error, I'm still a bit puzzled why it didn't work. other than that the indexing on the corners is permuted, the corner locations seem to fit well. unfortunately, without your mesh file it's hard to debug that. for example, not sure if a cubit command like `compress all sort` would help to avoid this.

the parameter `TOLERANCE_FACE_DETECTION` is a factor used to identify the midpoint of a given element face. the distance between the target midpoint and all face midpoints is then compared to this factor times the edge length of the element. since this factor multiplies with the element edge length, it usually avoids problems if the mesh elements are large or small.

regarding choosing a sufficiently small DT, the `output_generate_database.txt` file contains some output info to suggest a maximum DT size based on some heuristic CFL condition values, like:
```
...
*** Maximum suggested time step =    4.86940965E-02
...
```

**Comment by eikmeier-cn** [comment]
Thanks for the feedback, @danielpeter.
