### ISSUE TITLE
workflow for inverse problems: make the inversion tools more standard and more user-friendly

### ISSUE THREAD

**Issue by mpbl** [geodynamics/specfem3d#23]
Update from Dimitri, Oct 2012: after talking with many developers and users, we should definitely make the inversion tools in SPECFEM3D more standard and more user friendly. Even if there are many options to adjust when solving inverse problems, and different users currently have different tools (in Matlab, Perl, Fortran, Python and so on), sooner rather than later we should probably try to define a single tool in which all these different options could be implemented, but at least we would have a unified framework, which we could document in the manual.

Currently many users complain that computing sensitivity kernels is easy with SPECFEM3D but that then it is not so easy to use them (and different people give different answers when they are asked). So far, at least the following groups have local tools: the Princeton group, the Toronto group, Carl in Alaska, Emanuele and his group at INGV, Alessia (at least for Flexwin, there are now two versions: in Fortran and in Python), and the Marseille / CNRS group. We should try to address this issue relatively quickly, because the more we wait the more these sets of tools will diverge.

One thing we should do quickly for sure is make sure we maintain the current tools of SPECFEM3D inside the same directory as SPECFEM3D itself; it seems that currently everything is outside, in an "ADJOINT_TOMO" directory, which is thus not downloaded by users when they get SPECFEM3D through SVN or from the CIG tar file; which is problematic.

**Comment by komatits** [comment]
Done by Ryan and the Princeton group, here in our group Vadim Monteiller is also working on that and is almost done.

**Comment by komatits** [comment]
Reopened this issue, since the topic is currently being discussed by developers.

**Comment by komatits** [comment]
From Youyi Ruan, April 28, 2015:

The Seisstar website is built in order to host all the tools we are currently using for our global adjoint tomography and seismic imaging projects, and serves as an online library.  We hope bringing all the resources together in one place will help other users to access these tools easily.  Each package is hosted and maintained independently in their own Github repositories or websites. 

Wenjie is in charge of the Seisstar website, so he and individual authors may know more about the current status of these packages. 

I can speak part of these projects to my best knowledge, 
James, Lion and Matthieu are the main developers of ASDF toolboxes, they have finished the pyasdf package and implementing ASDF into SPECFEM3D.  

Wenjie,  Lion, Yanhua and myself are involved in the development of pre-processing workflows within a python framework, we have finished the pycmt3D (ready for beta release) and pyflex, and testing the multi-taper part of pyadjoint. 

I think Seisstar is an open place and welcomes any contributors, and all we want is encouraging more people to try it.

**Comment by komatits** [comment]
From Ryan Modrak, April 29, 2015:

To add to Youyi's descriptions, let me try to summarize the Python inversion packages.  Any additions, comments, or corrections are most welcome.

------------------------------------------
PySIT provides time- and frequency-domain waveform inversion capabilities.  Rather than a set of preassembled workflows, PySIT is toolkit through which users can script their own workflows.  Putting together migrations or inversions with PySIT is easy and flexible, in our experience. 

As a flexible Python inversion toolkit, PySIT seems well suited to research and development.  It is hard to judge how adaptable it is to production runs or to high performance environments.  Because of an absence of portability/scalability features, it probably works best for small or medium scale inversions.

Forward and adjoint simulations are carried out with built-in 2D or 3D TDFD or FDFD solvers.  Written in C with Python bindings, these solvers are very well integrated with other inversion components.  Use of built-in solvers rather than  external solvers avoids the need for complicated wrappers and makes the package easy to maintain, and hence robust.

Because of fundamental design issues, it is not possible, or at least not practical, to use PySIT and SPECFEM in the same workflow.  This was the main factor behind our decision to develop SeisFlows.

PySIT was written by Russell Hewitt, who has a background in applied math and computer science.  Through a mutual connection with Total, our group has visits and discussions with him. 


------------------------------------------
LASIF is an interactive tool for processing data and launching simulations.  Postprocessing and nonlinear optimization are not currently included.  The work of a model update must be performed manually. 

To a greater degree than other packages, LASIF is specialized for regional and global inversion.  A major aspect of the interface is a fixed directory tree, which acts as a data structure containing the entire state of the inversion.  With some tradeoffs when it comes to flexibility and possibility for abstraction, this approach has the advantage of being clear and simple, with directory names that make sense to regional and global seismologists.

As an interactive tool, adaptability to high performance environments is presumably limited.  Because nonlinear optimization and workflow management capabilities are not currently included, LASIF cannot be used be as the basis for an automated inversion, though it is worth checking with Lion Krischner as new features may be in planning or development.

Besides developing LASIF, Lion Krischner is one of the main developers of obspy and our collaborator on data format issues.  We have had extensive discussion with him about workflow issues, among other things.


------------------------------------------
SeisFlows is a Python waveform inversion package with both research and production capabilities, suitable for inexpensive 2D inversions through expensive 3D global 1 chunk inversions.

SeisFlows contains ready-to-go inversion and migration workflows, which can be adapted to individual user needs.  To provide this flexibility, there is a plugin system through which users are offered choices in each of the following categories: workflow, system, solver, optimization, preprocessing, and postprocessing.  In general, the tradeoff is a somewhat higher level of abstraction in exchange for greater flexibility and robustness. 

While base classes are provided for all six categories above, special attention is paid to the optimization base class.  Relative to NLCG, computational savings of roughly 50 percent can be realized with L-BFGS and an efficient line search in the majority of regional, global, and exploration problems.  In the preprocessing base class, obspy, pyadjoint, and pyflex integration is currently in progress.

The easiest way to learn more about SeisFlows is to run some examples.  If you have a Princeton account, simply follow the instructions in the SeisFlows documentation for running inversions on Tiger.  If you do not have Princeton account, feel free to contact me to learn how to install and run it on your own cluster.


------------------------------------------
ASKI is described on its webpage as a waveform inversion package.  At a glance though, it seems disconnected from mainstream waveform inversion. 

Among other issues, the documentation states that, in carrying out a model update, a "sensitivity matrix is explicitly assembled" and a "linear system is solved using LAPACK libraries".  In other words, model updates are computed using a full Newton method, which (can be very costly).

**Comment by schumf** [comment]
Replying to [the above comment](https://github.com/geodynamics/specfem3d/issues/23#issuecomment-97622479) (30 Apr 2015) on the Gauss Newton method of [ASKI](http://www.rub.de/aski) being very costly, I would like to mention the [2007 GJI paper by Chen et al.](https://doi.org/10.1111/j.1365-246X.2007.03429.x). They compare scattering-integral-based Gauss Newton FWI (which constitutes the methodology used by ASKI) with the adjoint conjugate-gradient method, with regard to computational expenses. They find that, in terms of the number of simulations to be done, scattering-integral-based inversion is more efficient than the adjoint conjugate-gradient method except for the case that the number of receiver components strongly exceeds the number of sources (threshold that can be deduced from the paper: number of receiver components being 23 to 41 times higher than the number of sources). 

Obviously you pay this efficiency in the number of simulations by requiring to store complete wavefield information to hard disk. ASKI addresses this problem by using the frequency domain (storing spectral wavefields at only a small number of frequencies per iteration) and by pre-integration of the kernels onto an independent (in general much coarser) inversion grid that can be chosen according to the resolutional power of the inverted data. In our [2016 GJI paper on the methodology of ASKI](https://doi.org/10.1093/gji/ggv505) we discuss these aspects in detail, give examples and argue that scattering-integral-based FWI thus becomes feasible today, even on regional scale.

**Comment by rmodrak** [comment]
I see that ASKI has been made to interface with both time- and frequency-domain forward solvers.  While it is true that full Newton or Gauss Newton in the frequency domain is more efficient than in the time domain, it is simply not correct that full Newton or Gauss Newton is competitive with conjugate gradient or quasi-Newton methods either for seismic waveform inversion or general large-scale nonlinear optimization (see for example the chapter “Large-scale unconstrained optimization” in Nocedal and Wright or the review article “Numerical methods for large-scale nonlinear optimization” by Gould et al).  One may be able to get around the huge cost in time, memory, or disk space of working with the full Hessian or Jacobian by projecting (preintegrating) onto a coarse basis, but only by working at a much coarser spacing than the resolution limit of seismic data at commonly used bandwidths.

It is problematic I think that Chen et al or Schumacher et al do not connect with the well-developed numerical optimization literature reviewed by Nocedal and Wright or Gould et al.  Are you aware of truncated Newton methods?  This is the approach actually taken by Akcelik et al and Epanomeritakis et al, whom you cite.  The idea is to avoid full matrix assembly by working only with the action of the Hessian or Jacobian. Given than you submitted to GJI, I’m surprised, didn’t editors Metivier or Virieux have anything to say?  Their work on applying truncated Newton methods to waveform inversion is becoming well known.

**Comment by schumf** [comment]
My motivation of giving [my last comment](https://github.com/geodynamics/specfem3d/issues/23#issuecomment-193656321) was to make aware of the improvements we suggest in our GJI paper in order to make FWI based on waveform Fréchet kernels derived from Born scattering (in the context of Parker's "Geophysical Inverse Theory", 1994) more feasible for practical application, thus I intended to relax the very general statement "which can be very costly" at the end of the [third last comment](https://github.com/geodynamics/specfem3d/issues/23#issuecomment-97622479). [In our paper](https://doi.org/10.1093/gji/ggv505) we discuss in detail advantages as well as challenges arising from such a modified approach to what Chen et al. call "scattering-integral method". It is not apparent to us, why [Chen et al.s'](https://doi.org/10.1111/j.1365-246X.2007.03429.x) comparison of computational costs, to which we refer (Table 1 in their paper), is wrong. 

It is certainly true that it depends on the specific seismic inversion problem whether the scattering-integral or the adjoint conjugate-gradient method, as compared by Chen et al., is more computationally expensive. ASKI simply offers an alternative approach, which eventually has to be chosen by the applicant, of course, depending on the problem to tackle.

**Comment by rmodrak** [comment]
At a glance, it is difficult to tell what exactly Chen et al are comparing,
because they ignore the the standard terminology of numerical optimization,
as well as the work of other seismologists, particularly those in
exploration geophysics, who routinely use this terminology.



Also at glance, however, it is clear that the main work of ASKI does
involve fully assembling and solving a linear system, which is very costly.


One way to put it is that any approach that involves fully assembling and
solving a linear system is uncompetitive for large problems.   In waveform
inversion, the size of the model vector is on the order of millions to
billions.   The size of the Hessian is the square of that, so working with
the fully assembled matrix is extremely inefficient.



More detailed calculations bear this out.  A typical mesh in a regional,
global or near surface seismology is roughly on the order of 500 x 500 x
500 grid points.  (Since we are on a spectral element solver forum, I
believe the coarsest mesh that handles surface wave propagation without
artifacts is something like 128 x 128 elements at Earth’s surface, 640 x
640 integration points or so?)  At this coarseness, you resolve periods as
low as 20 s. With a dispersion condition for the mesh of about 5 grid
points per wavelength, the resolution limit for waveform inversion is about
twice the grid spacing.  The memory or disk space requirements for such an
inversion translate to mid terabytes to mid petabytes.  By working with the
action of the Hessian rather than the fully assembled matrix, this storage
burden can be almost entirely avoided.  Projecting to a coarser mesh may
make full assembly feasible, but it provides no substitute for instead
working with the action of the matrix operator rather than the assembled
matrix.

**Comment by schumf** [comment]
ASKI is not yet capable of global-scale FWI at high frequencies, and nobody ever claimed it was. Again, it certainly depends on the problems which method is favourable.

So far, we have applied ASKI e.g. to the Aegean, inverting data with up to 0.1 Hz frequency content (our 2016 GJI paper, section 4.2). Setting up and solving the full linear system (67.320 unknowns, 140.140 sensitivity equations, plus 134.640 sparse regularization equations) by a parallelized CG algorithm is negligible in terms of computation time (less than 0.1 percent) compared with solving the forward problem (regularly, not by path-specific approach) and computing the kernels.

ASKI, furthermore, does not perform coarsening just for the sake of computational feasibility, but instead aims at choosing an unstructured spatial model description that explicitly tries to exploit the locally varying resolving power of the inverted data, trying to avoid setting up insignificant parts of the sensitivity matrix, hence trying to reduce the Nullspace of the inverse problem. I suggest having a closer "glance" at our paper.

**Comment by rmodrak** [comment]
I looked closely at your package not long ago.  I believe you should have a
glance at the numerical optimization literature before claiming in the
title of your paper that your package is computationally efficient.

**Comment by komatits** [comment]
See also https://github.com/geodynamics/specfem3d/issues/292
