### ISSUE TITLE
Cavity option in the internal mesher

### ISSUE THREAD

**Issue by homnath** [geodynamics/specfem3d#625]
Hi all,

We are adding an option to create a simple cavity for our tunnel project in the internal mesher. Currently, we add a line CAVITY_FILE = cavity.dat in Mesh_par_file but that will break the older input files. Since it is just a specific problem, another option is to add command line option which does not break older input files or do not commit this change at all in the package?

What do you think?

Thanks,
Hom Nath

**Comment by komatits** [comment]
Hi,

Please add it to the Par_file (and use the script in the EXAMPLES directory to add it to all Par_files).

Thanks,
Dimitri.

**Comment by danielpeter** [comment]
Hi Hom Nath,

i agree with Dimitri. it doesn't hurt to extend the parameter settings a bit. this happens all the time... and we will need to release a new version anyway soon, so just add it now before the next release :) 

my suggestion with this kind of add-ons is that if it is a single new option, just add it to the Mesh_Par_file and you could use the script in EXAMPLES/ folder like: 

./EXAMPLES/process_DATA_Par_files_to_update_their_parameters_from_a_master.py  my_new_Mesh_Par_file [0/1]

to automatically update all other Mesh_Par_file files in the package. 

additionally, you probably want to add another option USE_CAVITY_MODE = .true. to check whether that cavity feature will be active or not in the mesher.

if you plan to have several additional options for your cavity case, then maybe something like we're doing for faults would be best, i.e. you check for the presence of a Mesh_Par_file_cavity file which includes all your specifics. if that file doesn't exist, then the mesher will just run the default case.

best wishes,
daniel

**Comment by homnath** [comment]
Thanks for the comments/suggestions. We will add our changes soon.

**Comment by komatits** [comment]
Hi Hom Nath @homnath ,

Any update on that?

Thanks,
Dimitri.

**Comment by homnath** [comment]
Hi Dimitri,

Dimitry has successfully tested the implementation, and I am trying to
improve the PML speed based on your instructions. Once that is complete I
will make a pull request.

Best,
Hom Nath

**Comment by komatits** [comment]
Hi Hom Nath @homnath ,

Thanks! Perfect. Please make sure you keep Vadim @vmont informed because he is also working on PML (in collaboration in Bence @bencesolymosi ), thus let us make sure the two sets of improvements do not conflict. (Vadim and Bence are mostly working on how to easily add PML layers to existing CUBIT meshes, and Vadim is also working on a parallel version of xdecompose_mesh , in which he will thus need to input the PML weights; thus once you are done optimizing the PML code we should recompute the PML timings and use them as weights in the domain decomposer.

Thanks,
Dimitri.

**Comment by komatits** [comment]
Done by Hom Nath.
